### ISSUE TITLE
o7

### ISSUE THREAD

**Issue by DqRN** [jcardama/csgo-market-sniper#1]
not an issue, just wondering how you go about using a vpn and whether that stops the to many requests thing?

**Comment by jcardama** [comment]
@DqRN I'm planning to re-write the bot to use Puppeteer and BrightData in order for the bot to use proxy rotation, that way you won't need to use a VPN. Will update once I have a more concrete implementation of it.

**Comment by DqRN** [comment]
after that start charging people haha

**Comment by jcardama** [comment]
Closing as the bot now has proxy support.
