### ISSUE TITLE
CSGO float error

### ISSUE THREAD

**Issue by Cheezy1234** [jcardama/csgo-market-sniper#12]
when I use brightdata datacenter proxy i get this error for every item on every page.
![image](https://github.com/jcardama/csgo-market-sniper/assets/131748333/1089ae50-9a71-4656-b788-5c644f2d48b4)

I dont get this when I dont use the proxy so I dont really know how to fix it. Any suggestions would help.

**Comment by Cheezy1234** [comment]
UPDATE: Ok well after trying it a few more times it appears like sometimes it works fine and other times it does not work at all and other times it crashes. I believe that the proxy is causing all of these problems as it wasn't happening before. I will try to work it out.

**Comment by jcardama** [comment]
> UPDATE: Ok well after trying it a few more times it appears like sometimes it works fine and other times it does not work at all and other times it crashes. What happens most times is it will launch and start running fine, then I will get rate limited and it will crash. If there is a way to control when the proxy switches IP's I think that might help.

In most cases yeah, you're getting rate-limited, seems CSGOFloat is more restrictive towards Proxies and rate-limits them more often. From the bot's end don't think there is a way to force a new IP, will investigate though.
