### ISSUE TITLE
adding Proxy issue

### ISSUE THREAD

**Issue by Cheezy1234** [jcardama/csgo-market-sniper#15]
So I am currently using brightdata proxy and was able to add the original host that it gave me (zproxy.lum-superproxy.io:22225) along with the username and password and it was working. However, I was looking to have a rotating ip proxy and to do that I went to the proxy manager and created a new proxy port:
![image](https://github.com/jcardama/csgo-market-sniper/assets/131748333/f17cdd20-5ace-4248-932e-8d221f69cff5)
So I now assume that this port will rotate through different proxy ip's. (i don't know much about this stuff)

When I tried to now change the config file to the new port:
![image](https://github.com/jcardama/csgo-market-sniper/assets/131748333/cc4b1b5f-e62c-4408-a971-0f16227cdeb7)

I received the following when I try to log in:
![image](https://github.com/jcardama/csgo-market-sniper/assets/131748333/26f2640a-1132-4d8c-b14b-8050442d2d79)

I am not too sure how to make this all work together (my end goal is to have multiple instances open each with a different IP or rotating IP so that I don't get rate limited.)

If I am doing something wrong or if anyone has suggestions or tutorials please let me know, anything helps.

**Comment by notcreeperdude** [comment]
well, 127.0.0.1 is the ip for localhost, not a remote IP. So youre connecting to your local host here and not the proxy

**Comment by Cheezy1234** [comment]
> well, 127.0.0.1 is the ip for localhost, not a remote IP. So youre connecting to your local host here and not the proxy

so when I add this to the end after the user and password ((zproxy.lum-superproxy.io:22225)) I get it to work but do i need to change the port number from 22225 to the one I configured to rotate (24000) because when I do that nothing will load.

**Comment by jcardama** [comment]
> > well, 127.0.0.1 is the ip for localhost, not a remote IP. So youre connecting to your local host here and not the proxy
> 
> so when I add this to the end after the user and password ((zproxy.lum-superproxy.io:22225)) I get it to work but do i need to change the port number from 22225 to the one I configured to rotate (24000) because when I do that nothing will load.

Were you able to configure it? Note that the format is as follows:
`username`:`password`@`proxyurl`:`port`

Note that the port should be the one that the proxy provider assigns to you.

**Comment by Cheezy1234** [comment]
Ok well I seem to be able to log in now but I an now getting this error and crash right after it tries to start: 
![image](https://github.com/jcardama/csgo-market-sniper/assets/131748333/9088957c-8cd5-43f9-867a-15c6c6ebe85e)

**Comment by Stefanalf** [comment]
Yo, did you solve it? Trying out the same with residential proxy

**Comment by Cheezy1234** [comment]
> Yo, did you solve it? Trying out the same with residential proxy

yes i solved it, are you having the same issue? if you are explain the problem you have and i might be able to help.

**Comment by Stefanalf** [comment]
> 

Hmm, I think I'll not use it as mcuh for a proxy to be "worth" atm. But maybe you could explain what I did wrong if I were to use it in the future. So I sed a trail from brightdata with residential proxy and Im following this format(username:password@proxyurl:port). So  username:password@zproxy.lum-superproxy.io:22225 with my own username and password. Im thinking that the zproxy.lum.. should be the ip, if so do you know where to find it?

**Comment by Cheezy1234** [comment]
> > 
> 
> Hmm, I think I'll not use it as mcuh for a proxy to be "worth" atm. But maybe you could explain what I did wrong if I were to use it in the future. So I sed a trail from brightdata with residential proxy and Im following this format(username:password@proxyurl:port). So username:[password@zproxy.lum-superproxy.io](mailto:password@zproxy.lum-superproxy.io):22225 with my own username and password. Im thinking that the zproxy.lum.. should be the ip, if so do you know where to find it?

you should use one of these data center settings: 
![image](https://github.com/jcardama/csgo-market-sniper/assets/131748333/53b7b5d3-a29e-4d35-916e-8f78b775529d)
it will end up being much cheaper and the result will be the same. and your format should be correct how you had it. let me know if you have an issue setting it up.

**Comment by Stefanalf** [comment]
I tried it and it worked without any problem, dont know what went wrong with residental proxy. So what settings do you use for data center, do you have multiple IPs? And I assume monthly fee is cheaper than just paying for each gb

**Comment by Cheezy1234** [comment]
> I tried it and it worked without any problem, dont know what went wrong with residental proxy. So what settings do you use for data center, do you have multiple IPs? And I assume monthly fee is cheaper than just paying for each gb

im still figuring it out but right now i have 3 ip's. I am trying to figure out how to run it so I dont get rate limited.
