### ISSUE TITLE
Cant open the bot.

### ISSUE THREAD

**Issue by Cryptabey** [jcardama/csgo-market-sniper#2]
Hi, when I do python main.py it doesn't do anything no error message nothing and I don't even seem to have a main.py file. I also tried the same thing doing python "filename" with every python file I saw and it never gives me any errors it just doesn't do anything.

**Comment by jcardama** [comment]
> Hi, when I do python main.py it doesn't do anything no error message nothing and I don't even seem to have a main.py file. I also tried the same thing doing python "filename" with every python file I saw and it never gives me any errors it just doesn't do anything.

Make sure you have Python v3.10 installed.
Also make sure you install all the required dependencies by running: `pip install -r .\settings\requirements.txt`
Once you've made sure of the previous, run the following command: `python csgo-market-sniper.py`

**Comment by jcardama** [comment]
I have updated the README to fix the instructions on how to install and run the bot!
