### ISSUE TITLE
works fine for one skin but as soon as it has finished on the first skin it crashes and outputs this 

### ISSUE THREAD

**Issue by rzrv** [jcardama/csgo-market-sniper#20]
Browser instance closed.
Goodbye!
Traceback (most recent call last):
  File "C:\Users\\OneDrive\Desktop\csgo-market-sniper-main (1)\csgo-market-sniper-main\csgo-market-sniper.py", line 83, in <module>
    main()
  File "C:\Users\\OneDrive\Desktop\csgo-market-sniper-main (1)\csgo-market-sniper-main\csgo-market-sniper.py", line 65, in main
    process_skin_marketplace(config, driver, skin, skin_index)
  File "C:\Users\\OneDrive\Desktop\csgo-market-sniper-main (1)\csgo-market-sniper-main\functions.py", line 511, in process_skin_marketplace
    page_count = get_page_count(driver, maximum_pages)
  File "C:\Users\\OneDrive\Desktop\csgo-market-sniper-main (1)\csgo-market-sniper-main\functions.py", line 154, in get_page_count
    return get_min_of_two(last_page_number, max_page_count)
  File "C:\Users\\OneDrive\Desktop\csgo-market-sniper-main (1)\csgo-market-sniper-main\functions.py", line 133, in get_min_of_two
    return min(num1, num2)
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by Cheezy1234** [comment]
> Browser instance closed. Goodbye! Traceback (most recent call last): File "C:\Users\OneDrive\Desktop\csgo-market-sniper-main (1)\csgo-market-sniper-main\csgo-market-sniper.py", line 83, in main() File "C:\Users\OneDrive\Desktop\csgo-market-sniper-main (1)\csgo-market-sniper-main\csgo-market-sniper.py", line 65, in main process_skin_marketplace(config, driver, skin, skin_index) File "C:\Users\OneDrive\Desktop\csgo-market-sniper-main (1)\csgo-market-sniper-main\functions.py", line 511, in process_skin_marketplace page_count = get_page_count(driver, maximum_pages) File "C:\Users\OneDrive\Desktop\csgo-market-sniper-main (1)\csgo-market-sniper-main\functions.py", line 154, in get_page_count return get_min_of_two(last_page_number, max_page_count) File "C:\Users\OneDrive\Desktop\csgo-market-sniper-main (1)\csgo-market-sniper-main\functions.py", line 133, in get_min_of_two return min(num1, num2) TypeError: '<' not supported between instances of 'str' and 'int'

send a screenshot of your config

**Comment by rzrv** [comment]
> 

seems to be patterns r the issue. is there a pattern limit at all?

**Comment by Cheezy1234** [comment]
> Author

i dont think so, just make sure it is in the right format

**Comment by rzrv** [comment]
> > Author
> 
> i dont think so, just make sure it is in the right format

yep theres a limit to the amount of patterns i have done multiple testing's using the same config just less patterns and their is a pattern limit

**Comment by rzrv** [comment]
> > Author
> 
> i dont think so, just make sure it is in the right format

the amount of patterns was a problem was inputing to much at the same time

**Comment by rzrv** [comment]
got it to work by splitting up the patterns so instead of looking for all at once i split it by 3 and loaded the same skin 3 times with differetn patterns
