### ISSUE TITLE
CSGOFloat Rate limit perhaps?

### ISSUE THREAD

**Issue by notcreeperdude** [jcardama/csgo-market-sniper#3]
![image](https://user-images.githubusercontent.com/75228915/236960351-8b047412-a0ce-4976-838e-72f2ead90e75.png)

Seems like the CSGOFloat extension rate limits and therefore the whole thing breaks. Any way to fix?

**Comment by notcreeperdude** [comment]
It seems that turning off my wireguard proxy then back on does the trick so its definitley a rate limit. Would it be possible to add wireguard support and have it auto reconnect if it encounters this error?

**Comment by Cheezy1234** [comment]
I have also been getting this today, it was working fine yesterday so I think it might just be csgofloat servers being full at the moment. 
![image](https://user-images.githubusercontent.com/131748333/236961932-cc0aa087-f095-47d7-b1c5-e848ef18474a.png)

**Comment by jcardama** [comment]
This is a known CSGOFloat problem as Valve has heavily limited the request rate, that is why they removed the ability for bots to use their API and had to sort to use the extension, but still they are rate limited by Valve. 

I'm looking into adding proxy support to the bot with rotating IP's but still if CSGOFloat is rate limited by Valve no matter if we use a proxy or not it will always return that error.

**Comment by jcardama** [comment]
Will close as the bot now has proxy support that hopefully mitigates this issue.
