### ISSUE TITLE
bot bought random thing

### ISSUE THREAD

**Issue by Andrewrd364** [jcardama/csgo-market-sniper#4]
![image](https://github.com/jcardama/csgo-market-sniper/assets/133220836/5ecf0041-54fb-472a-9d04-908216526f33)
I have this in my config file, but somehow bot bought this pattern.
![image](https://github.com/jcardama/csgo-market-sniper/assets/133220836/13b19005-2318-4a19-97b9-538583238c45)
Im afraid to start bot again because he can buy some trash that i dont need. And in the log file it says different float value.
![image](https://github.com/jcardama/csgo-market-sniper/assets/133220836/07ebc822-eeac-4657-a086-fefe2e95552e)

**Comment by notcreeperdude** [comment]
Hmm, perhaps the thing you were looking for did exist but it just grabbed the wrong buy button?

**Comment by jcardama** [comment]
> Hmm, perhaps the thing you were looking for did exist but it just grabbed the wrong buy button?

This could be the case, will adjust some things to make sure the item the bot finds is the one it buys.

**Comment by jcardama** [comment]
With the new release I've improved the logic so that it purchases the correct skin when the criteria for each one is met.
