### ISSUE TITLE
Sorting by low float unnecesarily

### ISSUE THREAD

**Issue by notcreeperdude** [jcardama/csgo-market-sniper#5]
for example, trying to snipe blue gem patterns. Float doesnt matter, only pattern. Float section is empty in the config. Bot sorts low to high float anyway causing them to not show up if theyre just listed for market price

**Comment by jcardama** [comment]
This is a valid observation, will make sorting by float a configurable option so that it can be turned on or off, on my use case which I need to find lower floats, it makes sense but in your case it doesn't.

**Comment by notcreeperdude** [comment]
Making it so its configurable per skin would be nice. Cause im also wanting low float acid fades for tradeups

**Comment by jcardama** [comment]
Makes sense, thanks for the suggestion!

**Comment by jcardama** [comment]
New release should address this.
