### ISSUE TITLE
Appears to be a storage leak somewhere

### ISSUE THREAD

**Issue by notcreeperdude** [jcardama/csgo-market-sniper#6]
Appears to be a storage leak somewhere. I Noticed the VM im running this on is filling up on storage slowly. This is the only program running on the VM and ive watched 1gb of files build up. Just trying to figure out where exactly and ill update

**Comment by jcardama** [comment]
Check for the buy.log it is the only file it is actively writing to, make sure it is of a reasonable size. If not, try restarting the VM if the storage is back to normal, it may be a memory leak. Could you verify that for me?

**Comment by notcreeperdude** [comment]
It may be google storing temp files when the pages are repeatedly loading

**Comment by jcardama** [comment]
Seems that it's an issue with Chrome itself, note that it needs google chrome present on the machine, that by itself can take a couple of hundred MB on the hard drive. Will close this comment and add as a possible improvement down the road.
